spring.config.import=optional:file:test.env[.properties]


# Configurações do banco de dados Oracle
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USUARIO}
spring.datasource.password=${DB_SENHA}


