spring.application.name=portalSolicitacaoInterna


  # Configurações do banco de dados Oracle
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USUARIO}
spring.datasource.password=${DB_SENHA}
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# Configurações adicionais do Hibernate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.jdbc.fetch_size=50
spring.flyway.validate-migration-naming=true
